### ISSUE TITLE
DUG 'Save-the-date'

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone-users-group#1]
See flyer from 2017: https://drive.google.com/drive/u/0/folders/0B_e2x_fMh6VbT1RyWmtBbFhzeVk

**Comment by aebudden** [comment]
Text for edit: https://docs.google.com/document/d/195YLNwRJMVjKpNj4SJM53bo7H97aHqFQISrnz84RnlA/edit

**Comment by rsandusky** [comment]
I updated the location, dates, theme, etc.

**Comment by karlbenedict** [comment]
I just updated it with some minor edits.

**Comment by aebudden** [comment]
Save the date complete - meeting with LT to discuss agenda and will confirm the meeting theme.

**Comment by rsandusky** [comment]
Should we distribute ‘save the date’ messages now or hold off?

Bob

**Comment by aebudden** [comment]
Flyers / postcards created (Register Now) and available on the DUG 2018 page for download / sharing. Also attached here.
[DUG2018_Flyer.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6b8f2122cf6d00119ba36c/125516c66e82c728ace21e0d46cca1bd71d2d2f1b0cfb35aa14fb2d86b56357c2301a03f32dfa17dbe1a2c530a5d1aa9445d5c16f8f9892af5e43d70dc0f5effcd7f1d2598694ef1e1c84afd13b0328a468fb7b9884fc9e03823e4838c483d0c48.pdf)
[DUG2018_Postcard.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6b8f2122cf6d00119ba36c/125516c66e82c728ace21e0d46cca1bd71d2d2f1b0d9b050b05ef1862d046b313916ac217586f76ae5002e0057584cf9430c5a41f9fadb2fa6b63d23d85d0bbb82384d68d47f40f2ecdd42e64bef62994597b7bb804dc5ea3e2cef8e894b3d190d1f9bb2.pdf)
