### ISSUE TITLE
Session 4: Sustainability Panel

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone-users-group#10]
1hr session.
Suggested panelists:
Bill/Rebecca/Suzie Allard
Tech Leadership
Outreach Leadership
Example MNs
Sponsors
Ben Halpern
Rep from an org that has undergone similar transition
Karl and Bob to moderate

**Comment by aebudden** [comment]
Intended format:
Karl/Bob to generate 'seed' questions in advance. Each panelist to give 2-3m introductory comments.
Attending DUG will have received advance reading material such as our product list, membership model ideas, examples.
The focus of the session is to be framed as the DUG giving input to DataONE in advance of the upcoming S&G meeting, using our materials an straw-man proposal as platform to initiate discussion.
Include in conversation "What does governance look lie?"

**Comment by aebudden** [comment]
Need to:
- [x] confirm panelists
- [ ] create advance materials
- [x] generate seed questions (Karl & Bob)
- [x] ensure panelist have prepared introductory remarks
- [ ] determine mechanism for capturing DUG feedback
- [x] develop survey instrument for anonymous feedback capture if desired

**Comment by karlbenedict** [comment]
Need to determine who will invite panelists - PDQ. 

Also assign other tasks to whomever needs to do them ... (see list above)

**Comment by karlbenedict** [comment]
Brian Heidorn invited to sustainability panel on 6/22.

**Comment by karlbenedict** [comment]
Charge to sustainability panel (Karl)

**Comment by aebudden** [comment]
Confirmed panelists:
Bill M, Erin R, Matt J, Amber B
Unconfirmed panelists:
Brian H (funder perspective)

**Comment by karlbenedict** [comment]
Questions: https://docs.google.com/document/d/1LXixRtowZuytG_1BBXWkuiExrbBko47JJ5QqLpdsZo0/edit
