### ISSUE TITLE
Session 5: Birds of a feather

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone-users-group#11]
1hr session, extending into 1 hr lunch as needed.

Community networking / unconference session focussed on topics put froward from the community. Can extend into lunch.

**Comment by aebudden** [comment]
@rkoskela To explore space / dining arrangements to see if we can have people take food into subgroups vs a plated lunch in a single dining area.

**Comment by aebudden** [comment]
Seed BoF with output from sustainability (products and prioritization, governance / organization structure / supporting infrastructure)

**Comment by karlbenedict** [comment]
Seeding from Sustainability won't work as the sustainability workshop is taking place *after* the DUG. Suggest we setup BOF sessions for brainstorming around sustainability of different aspects of network/community:

Three rooms = three BOFs


* infrastructure
* services
* software
* governance
* FAIR (Shelly)
* others ...

**Comment by aebudden** [comment]
I was referencing the DUG sustainability session occurring as part of the DUG meeting immediately before the BoF session.

**Comment by aebudden** [comment]
Shelley Stall also suggested FAIR as a discussion item.

**Comment by aebudden** [comment]
To be included in pre-meeting packet to go out mid next week
