### ISSUE TITLE
Session 7: Community

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone-users-group#14]
Community oral presentations. Currently soliciting abstracts until 6/10.
Session is 70 minutes which allows for 30m break before the poster session. Can extend and push back poster session or have no break (given posters is catered with cash bar and nibbles)

**Comment by karlbenedict** [comment]
So far a limited response to the request for submissions - the deadline has been extended.

**Comment by aebudden** [comment]
We have 3 talks allocated: Allen Lee, Shelley Stall and Bill Michener. I have closed the call for talks.

**Comment by aebudden** [comment]
The three submissions have been sent confirmation emails.
