### ISSUE TITLE
Session 8: Poster session

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone-users-group#15]

**Comment by rkoskela** [comment]
Now have 3 posters - 3rd is from Shelley Stall

**Comment by aebudden** [comment]
Shelley Stall is one of the three speakers. Is she also giving a poster? The form indicates talk and she may also do a BoF. I received communication to close the call for posters. Was this not confirmed during the meeting? Please advise.

**Comment by rkoskela** [comment]
Yes, Shelley will be doing a poster. Call for posters is not closed

**Comment by aebudden** [comment]
Correct, call for posters is not closed. I wanted confirmation post DUG that this was the action to take.
Did Shelley communicate via email that she wants a poster? Her registration form indicates a talk. Or is she doing both?

**Comment by rkoskela** [comment]
She's doing both - since we only had the 2 posters you submitted, I've been rounding up more.

**Comment by aebudden** [comment]
Great, thx. I hadn’t heard the final decision on keeping the call for posters open. I will continue to advertise.

**Comment by rkoskela** [comment]
6/26/2018: 4 posters as of today
Dave, Matt, Shelley Stall, Christine Laney
