### ISSUE TITLE
ESIP Workshop Development

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone-users-group#4]
With the new DUG model the intent is to have a one-day DUG meeting and a workshop within ESIP. The call for ESIP workshops has not yet been opened. Suggested topics for a workshop include:
Member nodes - MN showcase if cast as a session on contributing resource providers and usability of their services. 
Provenance a possibility for an ESIP event.

**Comment by aebudden** [comment]
Suggestion of two workshops as a sequential track: one on MNs and one on Prov. Need to determine individuals that will be available to help develop the workshop proposals.

**Comment by mbjones** [comment]
@aebudden We (led by @ludaesch) are discussing another ecology/archaeology/provenance meeting within WholeTale.  Would this make sense within the ESIP or DataONE DUG venues?

**Comment by aebudden** [comment]
@mbjones and @ludaesch If you are both planning to attend the DUG / ESIP I think that would be great. The next step in this process is for me to reach out to individuals that might be able to lead these efforts. Connecting with you both was on my list. I'm not sure how much of the archaeology community typically attend ESIP however this year it is in Arizona and we were going to reach out to tDAR given their geographic proximity.

**Comment by aebudden** [comment]
Provenance: I spoke with Annie Burgess who has been coordinating some ESIP provenance activities. We discussed having this workshop on the Tuesday and then an ESIP provenance session the following day.  The ESIP session is being written by that cohort and Matt Jones is inviting them to contribute to this workshop. There won't be duplication of content but they will be related and compliment one-another.
A 'space' for abstract development is here (https://docs.google.com/document/d/1zW59uSVIaYN37tezMw2E6s_ufJbFe9zeb1d2maGSK08/edit) with a link our to an AGU prov session abstract in development.

**Comment by karlbenedict** [comment]
We haven't historically had many archaeologists that attend the ESIP Federation meeting, and we might have some challenge getting many to come, just because Summer is the traditional field season for many folks. That having been said, a workshop that focuses on accessing and using environmental data provided by member nodes could have some appeal for those who are around (or would enjoy a day out of the heat of southern Arizona).

**Comment by aebudden** [comment]
Interoperability link: https://docs.google.com/document/d/1dYTmt9qaGhyXU6_DJv-9TrZ-_Fx_s24oqf89fJzgrmM/edit

**Comment by aebudden** [comment]
@mbjones @datadavev Please review the provenance workshop abstract. I need to submit this on Monday. https://docs.google.com/document/d/1zW59uSVIaYN37tezMw2E6s_ufJbFe9zeb1d2maGSK08/edit

**Comment by aebudden** [comment]
Both abstracts submitted
