### ISSUE TITLE
DUG Charter Review

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone-users-group#6]
Subgroup to review and propose changes to the charter in advance of the DUG.

**Comment by deboradrucker** [comment]
Debora Drucker

**Comment by karlbenedict** [comment]
not surprising - count me in.

**Comment by aebudden** [comment]
Editable charter available at: https://docs.google.com/document/d/1AL9tqs3s5dzb4XyihoVnukUKr5fSSwQgG669IGbo1KY/edit#. Please use suggested changes and comments to keep the original in tact.

**Comment by deboradrucker** [comment]
I did review it and made a couple of minor suggestions

**Comment by karlbenedict** [comment]
I did a review and inserted some comments. Primarily highlighting a need to consider what the post NSF governance model might look like as the current model is deeply embedded in the charter.

**Comment by karlbenedict** [comment]
Break into sections and do round-table discussions around different sections. Capture comments on shared online document. Also, potentially introduce the charter and provide the skeleton for meeting participants to fill in the blanks with their vision. Solicit participation in a group to develop a new charter.

**Comment by aebudden** [comment]
Please advise if we are now ready to send out the charter to the broader community. Also, should this go to the full DUG at this time, or only those registered for the DUG meeting?

**Comment by aebudden** [comment]
This has gone out to the DUG registrants and DUG membership. Some edits have come in. Charter linked from epad notes.
