### ISSUE TITLE
Session1: Overview

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone-users-group#7]
Welcome, Introduction to DataONE and updates. 30m session.

**Comment by rsandusky** [comment]
Assuming this will be the typical overview and project update?

**Comment by mbjones** [comment]
Yeah, but let's make it *exciting*  🎉 🎉 🎉

**Comment by aebudden** [comment]
Planning on playing music, having a countdown clock and then, in low baritone "Introducing your hosts for today's event: Karl Benedict and Robert Sanduskyyyyyyyyyy"

**Comment by aebudden** [comment]
Slides created
