### ISSUE TITLE
Session 2: MN Showcase

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/dataone-users-group#8]
30 minutes dedicated to an overview of the MN federation and a couple of 'showcase' presentations by MNs.
Need to identify which MNs will be present for the showcase. Also which DataONE team members will lead. Monica not attending the DUG.

**Comment by aforres4** [comment]
Question: are we skipping the "showcase" component?

**Comment by aebudden** [comment]
Is there an answer to Amy's question? We need to inform MNs if they are to present.

**Comment by rsandusky** [comment]
While on the call, Rebecca pointed out several people who have registered and represent MNs. I think it would be best for Amy to reach out to them to ask if they'd like to participate in the showcase session or, if they have one on hand, present a poster about their MN in the evening.

**Comment by aforres4** [comment]
MN Speakers Invited [6/26]:
Bob Sandusky- UIC: University of Illinois, Chicago (unique partnership) -VOLUNTOLD

Kerstin Lehnert - IEDA - Interdisciplinary Earth Data Alliance (up and coming MN) -CONFIRMED 6/26

Christine Laney,  - NEON:  National Ecological Observatory Network (recipient of such large NSF investment) - CONFIRM 7/9

**Comment by aebudden** [comment]
Amber to send Amy a link to the previous slide templates developed by Laura
